apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apps-ingress

spec:
  rules:
    - host: application.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: playground-service
                port:
                  number: 8888
